const words = [
    { word: "library", hint: "A place where books are stored and can be borrowed." },
    { word: "pyramid", hint: "A monumental structure built in ancient Egypt." },
    { word: "galaxy", hint: "A massive system of stars, planets, and other celestial bodies." },
    { word: "ocean", hint: "A large body of saltwater that covers most of the Earth's surface." },
    { word: "volcano", hint: "A mountain that erupts with lava, ash, and gases." },
    { word: "rainforest", hint: "A dense, tropical forest with high levels of rainfall." },
    { word: "butterfly", hint: "An insect with colorful wings that goes through metamorphosis." },
    { word: "hurricane", hint: "A powerful tropical storm with strong winds and heavy rain." },
    { word: "satellite", hint: "An object that orbits a planet or star." },
    { word: "microscope", hint: "A device used to magnify small objects." },
    { word: "telescope", hint: "A device used to observe distant objects in space." },
    { word: "desert", hint: "A barren area of land with little rainfall." },
    { word: "asteroid", hint: "A small rocky body that orbits the sun." },
    { word: "skeleton", hint: "The framework of bones that supports the body of an animal." },
    { word: "symphony", hint: "A large-scale musical composition for an orchestra." },
    { word: "aviation", hint: "The design, development, and operation of aircraft." },
    { word: "tornado", hint: "A violent rotating column of air extending from a thunderstorm to the ground." },
    { word: "ecosystem", hint: "A community of living organisms interacting with their environment." },
    { word: "monolith", hint: "A large, single upright block of stone." },
    { word: "crystal", hint: "A solid material with a regular, repeating pattern of atoms." },
    { word: "nebula", hint: "A cloud of gas and dust in space." },
    { word: "geology", hint: "The study of the Earth's physical structure and substance." },
    { word: "dynasty", hint: "A series of rulers from the same family." },
    { word: "anatomy", hint: "The study of the structure of living organisms." },
    { word: "gravity", hint: "The force that attracts objects toward the center of the Earth." },
    { word: "eclipse", hint: "An event where one celestial body moves into the shadow of another." },
    { word: "aviator", hint: "A person who operates an aircraft." },
    { word: "biodiversity", hint: "The variety of life in a particular habitat or ecosystem." },
    { word: "algorithm", hint: "A step-by-step procedure for solving a problem or performing a task." },
    { word: "latitude", hint: "The angular distance of a place north or south of the Earth's equator." },
    { word: "plasma", hint: "A state of matter consisting of ionized gas." },
    { word: "topography", hint: "The arrangement of natural and artificial physical features of an area." },
    { word: "mythology", hint: "A collection of myths, especially those belonging to a particular cultural tradition." },
    { word: "orbit", hint: "The path of a celestial body around another object in space." },
    { word: "quasar", hint: "A very bright and distant active galactic nucleus." },
    { word: "radiation", hint: "The emission of energy as electromagnetic waves or particles." },
    { word: "seismology", hint: "The study of earthquakes and seismic waves." },
    { word: "spectrum", hint: "A range of electromagnetic waves or a range of different things." },
    { word: "tectonic", hint: "Relating to the structure and movement of the Earth's crust." },
    { word: "vortex", hint: "A whirling mass of fluid or air." },
    { word: "xenon", hint: "A chemical element with the symbol Xe, a noble gas." },
    { word: "yoga", hint: "A physical, mental, and spiritual practice originating in ancient India." },
    { word: "zoology", hint: "The study of animals and their behavior." },
    { word: "oxygen", hint: "A gas that is essential for most forms of life on Earth." },
    { word: "genetics", hint: "The study of heredity and the variation of inherited characteristics." },
    { word: "nebula", hint: "A cloud of gas and dust in space, often a region where new stars are born." },
    { word: "quasar", hint: "A very energetic and distant active galactic nucleus." },
    { word: "molecule", hint: "A group of atoms bonded together, representing the smallest unit of a chemical compound." },
    { word: "eclipse", hint: "An event where one celestial body moves into the shadow of another." },
    { word: "galaxy", hint: "A system of millions or billions of stars, together with gas and dust, held together by gravitational attraction." },
    { word: "quantum", hint: "The minimum amount of any physical entity involved in an interaction." },
    { word: "bacterium", hint: "A microscopic single-celled organism that can cause disease." },
    { word: "asteroid", hint: "A small rocky body orbiting the sun, often found in the asteroid belt between Mars and Jupiter." },
    { word: "virus", hint: "A microscopic infectious agent that replicates only inside the living cells of an organism." },
    { word: "ecosystem", hint: "A biological community of interacting organisms and their physical environment." },
    { word: "kinetic", hint: "Relating to or resulting from motion." },
    { word: "crystal", hint: "A solid material whose atoms are arranged in a highly ordered, repeating pattern." },
    { word: "photosynthesis", hint: "The process by which green plants and some other organisms use sunlight to synthesize nutrients from carbon dioxide and water." },
    { word: "subatomic", hint: "Smaller than or occurring within an atom." },
    { word: "radiation", hint: "The emission of energy as electromagnetic waves or as moving subatomic particles, especially high-energy particles." },
    { word: "symbiosis", hint: "Interaction between two different organisms living in close physical association, typically to the advantage of both." },
    { word: "endothermic", hint: "A process or reaction that absorbs energy in the form of heat." },
    { word: "catalyst", hint: "A substance that increases the rate of a chemical reaction without itself undergoing any permanent chemical change." },
    { word: "evaporation", hint: "The process of turning from liquid into vapor." },
    { word: "neutron", hint: "A subatomic particle of about the same mass as a proton but without an electric charge, present in all atomic nuclei except those of ordinary hydrogen." },
    { word: "nucleus", hint: "The positively charged central core of an atom, consisting of protons and neutrons." },
    { word: "diffusion", hint: "The spreading of something more widely." },
    { word: "biome", hint: "A large naturally occurring community of flora and fauna occupying a major habitat." },
    { word: "ozone", hint: "A gas that forms a layer high in the atmosphere, protecting life on Earth by absorbing the sun's harmful ultraviolet rays." },
    { word: "chromosome", hint: "A thread-like structure of nucleic acids and protein found in the nucleus of most living cells, carrying genetic information in the form of genes." },
    { word: "hormone", hint: "A regulatory substance produced in an organism and transported in tissue fluids to stimulate specific cells or tissues into action." },
    { word: "isotope", hint: "Two or more forms of the same element that contain equal numbers of protons but different numbers of neutrons in their nuclei." },
    { word: "nucleic", hint: "Relating to or forming the nucleus of a cell." },
    { word: "oxidation", hint: "A process in which a chemical substance changes because of the addition of oxygen." },
    { word: "quantum", hint: "The minimum amount of any physical entity involved in an interaction." },
    { word: "refraction", hint: "The bending of a wave when it enters a medium where its speed is different." },
    { word: "solution", hint: "A homogeneous mixture composed of two or more substances." },
    { word: "ultraviolet", hint: "A type of electromagnetic radiation with a wavelength shorter than that of visible light but longer than X-rays." },
    { word: "vaccine", hint: "A substance used to stimulate the production of antibodies and provide immunity against one or several diseases." },
    { word: "wavelength", hint: "The distance between successive crests of a wave, especially points in a sound wave or electromagnetic wave." },
    { word: "xylem", hint: "The vascular tissue in plants that conducts water and dissolved nutrients upward from the root and also helps to form the woody element in the stem." },
    { word: "yeast", hint: "A microscopic fungus consisting of single oval cells that reproduce by budding, and are capable of converting sugar into alcohol and carbon dioxide." },
    { word: "zenith", hint: "The time at which something is most powerful or successful; the point in the sky or celestial sphere directly above an observer." },
    { word: "Acorn", hint: "Seed of an oak tree." }, 
    { word: "Bicycle", hint: "Two-wheeled vehicle." }, 
    { word: "Compass", hint: "Used for navigation." }, 
    { word: "Dolphin", hint: "Intelligent marine mammal." }, 
    { word: "Eclipse", hint: "Moon covers the sun." }, 
    { word: "Feather", hint: "Birds have them." }, 
    { word: "Glacier", hint: "Large ice mass." }, 
    { word: "Hammock", hint: "Used for relaxation." }, 
    { word: "Icicle", hint: "Hanging ice." },    
    { word: "Jewel", hint: "Precious stone." }, 
    { word: "Kangaroo", hint: "Jumps, has a pouch." }, 
    { word: "Lighthouse", hint: "Guides ships." }, 
    { word: "Meteor", hint: "Falling star." }, 
    { word: "Nectar", hint: "Flower's sweet liquid." }, 
    { word: "Oyster", hint: "Shellfish in the sea." }, 
    { word: "Pineapple", hint: "Tropical fruit." }, 
    { word: "Quartz", hint: "Common mineral." }, 
    { word: "Rainbow", hint: "Colorful arc in the sky." }, 
    { word: "Snowflake", hint: "Unique ice crystal." }, 
    { word: "Tornado", hint: "Violent rotating wind." }, 
    { word: "Umbrella", hint: "Used during rain." }, 
    { word: "Vineyard", hint: "Where grapes grow." }, 
    { word: "Whistle", hint: "Makes a sound when blown." }, 
    { word: "Xylophone", hint: "Percussion instrument." }, 
    { word: "Yacht", hint: "Luxury boat." }, 
    { word: "Zeppelin", hint: "Large airship." }, 
    { word: "Apricot", hint: "Small, orange fruit." }, 
    { word: "Balloon", hint: "Filled with air or helium." }, 
    { word: "Caterpillar", hint: "Turns into a butterfly." }, 
    { word: "Diamond", hint: "Hard, precious gem." }, 
    { word: "Eagle", hint: "Bird of prey." }, 
    { word: "Flamingo", hint: "Pink wading bird." }, 
    { word: "Giraffe", hint: "Tallest land animal." }, 
    { word: "Helicopter", hint: "Aircraft with rotating blades." }, 
    { word: "Ink", hint: "Used in pens." }, 
    { word: "Jaguar", hint: "Spotted big cat." }, 
    { word: "Kite", hint: "Flies in the wind." }, 
    { word: "Lemon", hint: "Sour citrus fruit." }, 
    { word: "Mountain", hint: "Tall natural elevation." }, 
    { word: "Nest", hint: "Bird's home." }, 
    { word: "Octopus", hint: "Eight-armed sea creature." }, 
    { word: "Penguin", hint: "Bird that swims." }, 
    { word: "Quokka", hint: "Happy small marsupial." }, 
    { word: "Raven", hint: "Black bird." }, 
    { word: "Seashell", hint: "Found on beaches." }, 
    { word: "Tiger", hint: "Large striped cat." }, 
    { word: "Urchin", hint: "Spiny sea creature." }, 
    { word: "Violet", hint: "Purple flower." }, 
    { word: "Waterfall", hint: "Flowing water over a cliff." }, 
    { word: "Xerox", hint: "Photocopy machine." }, 
    { word: "Yoga", hint: "Physical and mental practice." }, 
    { word: "Zebra", hint: "Striped animal." }, 
    { word: "Anchor", hint: "Keeps a ship steady." }, 
    { word: "Butterfly", hint: "Insect with colorful wings." }, 
    { word: "Candle", hint: "Wax with a wick." }, 
    { word: "Daisy", hint: "Simple white flower." }, 
    { word: "Eruption", hint: "Volcanic explosion." }, 
    { word: "Falcon", hint: "Fast-flying bird." }, 
    { word: "Garlic", hint: "Pungent bulb." }, 
    { word: "Hummingbird", hint: "Small, hovering bird." }, 
    { word: "Icicle", hint: "Hanging ice." }, 
    { word: "Jellyfish", hint: "Gelatinous sea creature." }, 
    { word: "Kangaroo", hint: "Jumps, has a pouch." }, 
    { word: "Lamp", hint: "Source of light." }, 
    { word: "Meerkat", hint: "Small mammal in groups." }, 
    { word: "Narwhal", hint: "Sea creature with a tusk." }, 
    { word: "Owl", hint: "Nocturnal bird." }, 
    { word: "Peacock", hint: "Bird with colorful feathers." }, 
    { word: "Quartz", hint: "Common crystal." }, 
    { word: "Raccoon", hint: "Masked nocturnal mammal." }, 
    { word: "Sunflower", hint: "Tall yellow flower." }, 
    { word: "Tarantula", hint: "Large, hairy spider." }, 
    { word: "Unicorn", hint: "Mythical horse with a horn." }, 
    { word: "Vine", hint: "Climbing plant." }, 
    { word: "Walrus", hint: "Marine mammal with tusks." }, 
    { word: "Xenon", hint: "Chemical element." }, 
    { word: "Yogurt", hint: "Cultured dairy product." }, 
    { word: "Zinnia", hint: "Type of flower." }, 
    { word: "Avocado", hint: "Green fruit with a pit." }, 
    { word: "Buffalo", hint: "Large grazing animal." }, 
    { word: "Cactus", hint: "Spiky desert plant." }, 
    { word: "Dolphin", hint: "Intelligent marine mammal." }, 
    { word: "Eagle", hint: "Bird of prey." }, 
    { word: "Falcon", hint: "Fast-flying bird." }, 
    { word: "Garden", hint: "Where plants grow." }, 
    { word: "Harp", hint: "Large stringed instrument." }, 
    { word: "Igloo", hint: "Eskimo house." }, 
    { word: "Jigsaw", hint: "Puzzle pieces." }, 
    { word: "Kite", hint: "Flies in the wind." }, 
    { word: "Ladder", hint: "Used for climbing." }, 
    { word: "Meteor", hint: "Falling star." }, 
    { word: "Nugget", hint: "Small gold piece." }, 
    { word: "Oyster", hint: "Shellfish." }, 
    { word: "Pyramid", hint: "Ancient Egyptian tomb." }, 
    { word: "Rocket", hint: "Launches into space." }, 
    { word: "Satellite", hint: "Orbits Earth." }, 
    { word: "Turtle", hint: "Reptile with a shell." }, 
    { word: "Unicorn", hint: "Mythical horse." }, 
    { word: "Volcano", hint: "Erupts with lava." }, 
    { word: "Waterfall", hint: "Flowing water over a cliff." }, 
    { word: "Xylophone", hint: "Musical instrument." }, 
    { word: "Yak", hint: "Long-haired bovid." }, 
    { word: "Zephyr", hint: "Gentle breeze." } 
      ];
  